# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CountryTopCharts' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CountryTopCharts
pod 'SDWebImage'
pod 'SDWebImageSVGCoder'

  target 'CountryTopChartsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CountryTopChartsUITests' do
    # Pods for testing
  end

end
